# Win32 build which can work on Win7 upwards.
version: 1.50.{build}
# base image
image: Visual Studio 2015

platform: Win32
configuration: Release       

install:
 
 - md OpenCV
 - cd OpenCV
 - ps: Start-FileDownload https://github.com/hn-88/opencvdeb/releases/download/v4.3.0.2/OpenCV.zip
 - 7z x OpenCV.zip
 - cmd: setx -m OpenCV_DIR C:\projects\ocvvid2fulldome\OpenCV\x86\vc14
#- cmd: setx path "%path%;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\bin;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\lib"
 - refreshenv
 - cd .. 

before_build:
  - cmd: git checkout v1.50
  
build:
  project: OCVvid2fulldomeWin32.vcxproj

  verbosity: minimal
 
artifacts:
- path: Release\OCVvid2fulldomeWin32.exe
  
    
