# Win64 build.
version: 1.60.{build}
# base image
image: Visual Studio 2019

platform: x64
configuration: Release       

install:
 
 - md OpenCV
 - cd OpenCV
 - ps: Start-FileDownload https://github.com/opencv/opencv/releases/download/4.7.0/opencv-4.7.0-windows.exe
 - 7z x opencv-4.7.0-windows.exe
 - cmd: setx -m OpenCV_DIR C:\projects\ocvvid2fulldome\opencv\build\x64\vc16
#- cmd: setx path "%path%;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\bin;C:\projects\ocvwarp\opencv-3.4.9\build\install\x86\vc14\lib"
 - refreshenv
 - cd .. 
  
  
build:
  project: OCVvid2fulldomeWin64.vcxproj

  verbosity: minimal
 
artifacts:
- path: Release\OCVvid2fulldomeWin64.exe
  
    
